### ISSUE TITLE
The cypress test failed

### ISSUE THREAD

**Issue by jasonLaster** [filiphric/things-app-react#11]
Looks like the `todo-item` selector is finding multiple elements

https://app.replay.io/recording/cypresse2especcyts--066c1063-0bdb-4d0d-a108-bed9b2d13229?point=17199483345498582503414409254142934&time=8289&focusWindow=eyJiZWdpbiI6eyJwb2ludCI6IjE0Mjc4ODE2MzYyMjMzNjU5Njc3NDEwNTk5MTI1Mzg1OTc4IiwidGltZSI6NjU2Mn0sImVuZCI6eyJwb2ludCI6IjE3ODQ4NTIwNDUyODY0MjY2Nzk0Mzg2ODM5NjkyMTE2OTcyIiwidGltZSI6ODUzMX19

**Comment by filiphric** [comment]
yeah it looks like there are multiple items with same `data-test` attribute
